### PR TITLE
Add CSS for soundcloud social link

### PR DESCRIPTION
**Pull request by r4nd0m6uy**
So we have a nice orange soundcloud theme circle around it.

I also had to change the "min" css manually in order to make it work. I don't know if that should be generated automatically ...

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
To generate the CSS you need to install `gulp`.

`npm install -g gulp`

Then inside the project run:

`npm install`

And after run:

`gulp`

**Comment by r4nd0m6uy** [comment]
Arrrgg nodejs :stuck_out_tongue_closed_eyes: ... !

Would you take this pull request or should I create a new one? However I tried the generation with gulp but nothing changed!
```
[moragu@moragu-vbox-dev:~/d/g/Flex] (sc_attempt2 ⚡)$ git diff
diff --git a/static/stylesheet/style.less b/static/stylesheet/style.less
index d60e24a..2a5c17f 100644
--- a/static/stylesheet/style.less
+++ b/static/stylesheet/style.less
@@ -403,6 +403,10 @@ ul.social {
   a.sc-reddit {
     background-color: #ff4500;
   }
+
+  a.sc-soundcloud {
+    background-color: #ff5500;
+  }
 }
 
 //
[moragu@moragu-vbox-dev:~/d/g/Flex] (sc_attempt2 ⚡)$ gulp
[moragu@moragu-vbox-dev:~/d/g/Flex] (sc_attempt2 ⚡)$ git status 
On branch sc_attempt2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   static/stylesheet/style.less

no changes added to commit (use "git add" and/or "git commit -a")
```
I have a VM with Ubuntu 14.04, shall I try with a more recent distro or am I a retarded?

**Comment by alexandrevicenzi** [comment]
@r4nd0m6uy Yep, nodejs, I dislike a little bit to. About ubuntu, well, how about a better distro? lol

So, just remove .css and .min.css from this commit. I'll generate the minified version here, as is working gulp here. :)

**Comment by r4nd0m6uy** [comment]
Agreed but I'm using here the distro my boss want to to use for development. Luckily I have a VM for testing with a more decent distro that has gulp working!

It should be hopefully good now!

**Pull request merged**
