### PR TITLE
Support highlight table

### PR DESCRIPTION
**Pull request by mizunashi-mana**
Pelican support syntax highlighting code-block for reStructuredText: https://docs.getpelican.com/en/4.0.1/content.html#syntax-highlighting

```rest
.. code-block::
  :linenos: table

  some code
```

is translated to

```html
<table class="highlighttable"><tbody>
  <tr>
    <td class="linenos">
      <div class="linenodiv">
        <pre>1</pre>
      </div>
    </td><td class="code">
      <div class="highlight">
        <pre><span></span>
        ...
        </pre>
      </div>
    </td>
  </tr>
</tbody></table>
```

Flex theme applies normal `table` style to `table.highlighttable` .
However, there are problems:

* Not working `overflow-x: auto` for `table.highlighttable pre` .
* redundant border
* redundant padding

This PR fix these.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@mizunashi-mana Do you have an example of the problem? No issue was created for that I guess.

**Comment by mizunashi-mana** [comment]
> @mizunashi-mana Do you have an example of the problem? No issue was created for that I guess.

Oh, it is my careless. I created new issue and added link to example project: https://github.com/alexandrevicenzi/Flex/issues/176#issue-434600645 . You can see the problem now.

**Comment by alexandrevicenzi** [comment]
@mizunashi-mana can you fix the conflict?

**Comment by mizunashi-mana** [comment]
@alexandrevicenzi fixed.

**Comment by alexandrevicenzi** [comment]
I will close and fix it in another patch as there are conflicts.

**Pull request closed without merging**
