### PR TITLE
Change ADD_THIS for working inline tool

### PR DESCRIPTION
**Pull request by dmytrolitvinov**
@alexandrevicenzi Change inline tool for Add This service. #85

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
This change will break my AddThis account. For those who have an old AddThis account, it will break. For those that have a new account, it will work.

This is not the solution I want. We need to find a way to get it working on both scenarios.

Also, this is a duplicate of #85.

**Comment by alexandrevicenzi** [comment]
@dmytrolitvinov just keep both code, it will work.

**Comment by dmytrolitvinov** [comment]
@alexandrevicenzi Change branch to support old settings AddThis accounts. Verify

**Comment by dmytrolitvinov** [comment]
@alexandrevicenzi Hi. Very strange. In my local dev publish content its work as expected, but in [prod server](https://dmytrolitvinov.github.io/blog/2017/02/23/improve-your-skill-with-games/) - not. Do you know what it can be?

**Comment by alexandrevicenzi** [comment]
@dmytrolitvinov Yeah, there are people complaining about "AdBlocker" blocking AddThis.

Another thing might be is if someone uses GitHub pages it can be cache related problem.

**Pull request merged**
