### PR TITLE
Isso support

### PR DESCRIPTION
**Pull request by sumnerevans**
Related to #177 

This PR adds support for using [Isso](https://posativ.org/isso/) for comment integration.

* I tried to model it after the Disqus integration.
* I tried to style the buttons in the Isso comments form after the buttons in the rest of Flex.
* Required parameter is `ISSO_URL` which is the URL of the Isso instance that you are using.
* Optional parameters:
  * `ISSO_EMBED_JS_PATH`: the path to the `embed.min.js` or `embed.dev.js` file for Isso. The default is to use the `isso.min.js` in `static/isso`.
  * `ISSO_OPTIONS`: a dictionary of Isso option to value. The `option` is automatically prepended with `data-isso-`. See https://posativ.org/isso/docs/configuration/client/ for all of the options.

Proof it works:

* An example article on my website that is currently using Isso is here: https://sumnerevans.com/2019/introducing-offlinemsmtp.html#introducing-offlinemsmtp
* Isso config for my website: https://gitlab.com/sumner/sumnerevans.com/-/blob/master/pelicanconf.py#L118

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
Can we include `embed.min.js` in this theme instead of pointing to a server?

**Comment by sumnerevans** [comment]
The reason I hesitated to do that is that the `embed.min.js` files change from release to release in Isso. If you are running an earlier version of Isso, a later version of the `embed.min.js` may not work.

However, I think that having `ISSO_EMBED_JS_PATH` default to the latest version of `embed.min.js` from the Isso project makes sense. That way, if you are running an old version, you can always override it, but if you are running the latest version of Isso, you don't have to do anything. I've updated my PR accordingly.

**Comment by sumnerevans** [comment]
Ok, I've removed the conflict with the `min.css` file.

**Comment by alexandrevicenzi** [comment]
BTW, you forgot to add Isso in README as a supported plugin, will be available in 2.3, I'll do the release later once all patches are merged.

**Comment by sumnerevans** [comment]
I've added to the README. I will add documentation to the Wiki once merged.

**Comment by alexandrevicenzi** [comment]
Thanks, this is a nice feature.

**Pull request merged**
