### PR TITLE
Add webassets support for CSS

### PR DESCRIPTION
**Pull request by mauricioabreu**
Change base template to add support for minified CSS files.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
Webassets is an external plugin, right?

I dislike this a little bit because you force someone to use a random plugin.

**Comment by mauricioabreu** [comment]
Agreed.
We can make it optional using a setting named `WEBASSETS`.
If still you don't like this we can close it.

Thanks for your feedback!

**Comment by alexandrevicenzi** [comment]
It's a good idea. But you could find a way to check if this plugin is enabled. Not sure how to do this.

**Comment by mauricioabreu** [comment]
Okay! Let me work on this to offer a good and non intrusive code.

**Comment by atodorov** [comment]
Hi guys,
I've tried to use the assets plugin based on whether it was loaded or not by using the following snippet:

```
 {% for name in PLUGINS if name == 'assets' %}
  {% assets %}
  {% endassets %}
{% else %}
  assets is disabled
{% endfor %}
```
This works fine when the plugin is loaded but failed miserably when it is not. The problem is Jinja, see https://github.com/pallets/jinja/pull/582.  At this moment I don't think this can be resolved easily.

**Comment by alexandrevicenzi** [comment]
See #40.

**Pull request closed without merging**
