### PR TITLE
support for representative_image plugin

### PR DESCRIPTION
**Pull request by smidm**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
A possible fix for #81.

**Comment by alexandrevicenzi** [comment]
@smidm So, there's no CSS? Does it work on mobile, desktop, multiple screen sizes?

I think it won't fit on mobile if you choose an image 1200x800 for example.

**Comment by smidm** [comment]
It seems that the images are properly scaled. Check it at 
http://cmp.felk.cvut.cz/~smidm/articles.html

**Comment by alexandrevicenzi** [comment]
Maybe because it gets the size of the parent element. :thinking: 

So, align Left or Center?

**Comment by smidm** [comment]
It is left aligned now and I find it ok.

**Comment by alexandrevicenzi** [comment]
@smidm Could you add to the Wiki how to use this feature?

**Comment by smidm** [comment]
I'll add it in a week, too busy now.

**Comment by smidm** [comment]
https://github.com/alexandrevicenzi/Flex/wiki/Custom-Settings

ok?

**Comment by alexandrevicenzi** [comment]
@smidm I think it's time to create a new doc for plugins.

We could have one that has all Flex plugins.

**Pull request merged**
