### PR TITLE
add doushuo

### PR DESCRIPTION
**Pull request by jswh**
[duoshuo] (http://duoshuo.com/) is a disqus-like comment plugin.It take a long time to load disqus in China.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@jswh Thanks. If you could add to the Wiki I appreciate.

**Comment by jswh** [comment]
I am very sorry to tell that duoshuo has stop its service since 2017/06/01.Thanks it for its free service since 2012.

**Comment by alexandrevicenzi** [comment]
@jswh maybe you can send a new PR.

**Comment by jswh** [comment]
This is the PR to remove it.https://github.com/alexandrevicenzi/Flex/pull/139

**Pull request merged**
