### PR TITLE
Extract translations and update french

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR extract translations to provide missing ones.

French translations are updated.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@noirbizarre where did you extracted this from? where did you update the french translation?

All translations are done in Transifex, there are languages with missing translations. There are new languages on Transifex that aren't in this repo yet.

If you want to update translations register on [Transifex](https://www.transifex.com/alexandrevicenzi/flex-pelican/) and I'll update it accordingly. If the base language is outdated on Transifex I need to update it.

**Comment by alexandrevicenzi** [comment]
@noirbizarre just in case, the strings on Transifex are outdated, I need to update it.

**Comment by alexandrevicenzi** [comment]
@noirbizarre can you translate on Transifex? The POT is up to date now.

https://www.transifex.com/alexandrevicenzi/flex-pelican/translate/#fr

**Comment by noirbizarre** [comment]
Done :+1: 

I close this PR

**Pull request closed without merging**
