### PR TITLE
Add support for admonitions

### PR DESCRIPTION
**Pull request by lpenaud**
Hi,
At first I have writen my own css file to add some style to admonitions, then I seen your milestone #187 so I do some modification on "less" files.
Here a overview to the different admonitions: 
image

Best regards,
Loïc Penaud

### CODE REVIEW

**Comment by crbn60** [comment]
That's great @lpenaud ! I was just looking at the CSS for admonitions as I need them.

**Comment by alexandrevicenzi** [comment]
If you change LESS files you need to compile it to generage min.css files.

What about following Bootstrap colors? Info = Blue, Success = Green and so on.

Perhaps would also be intereting to show some icons as proposed in the issue, there's FontAwesone icons available in this theme.

**Comment by lpenaud** [comment]
I add FontAwesome icons and I modify colors to be close to Bootstrap style.
A screenshot with the different admonitions:
image

I run build script to generate min.css files too.

**Comment by alexandrevicenzi** [comment]
@lpenaud why there are some font-awesone files in this PR? If you want to update it, please, do in another PR.

**Comment by lpenaud** [comment]
When I ran build script, gulp create new css files to font-awesome. Then I added all files to my commit, my bad.
However we should remove `font-awesome` to dependencies and remove `cp` gulp task because the version in npm is outdated.
Furthermore we might add `static/font-awesome` to `.gitignore` to avoid git added problem.

**Comment by alexandrevicenzi** [comment]
But I still dont get it why there's font awesome CSS in this PR. It should not be there as it's not part of this implementation.

**Comment by lpenaud** [comment]
Okay I removed font-awesome files, you can review it now.

**Comment by alexandrevicenzi** [comment]
@lpenaud thank you, feel free to send another PR with font awesome update if you want to.

**Pull request merged**
