### PR TITLE
Fix Monokai CSS file

### PR DESCRIPTION
**Pull request by Phyks**
As discussed in https://github.com/alexandrevicenzi/Flex/issues/119. There might be similar issues with other styles.

### CODE REVIEW

**Comment by Phyks** [comment]
I added a second commit to fix the render of period archives (typically yearly archives). Otherwise, the margins were not right.

**Comment by Phyks** [comment]
And I added the commit concerning the Google fonts, discussed in #112. It was easier for me to just append it to this PR, but I can split in multiple PRs if you want.

**Comment by alexandrevicenzi** [comment]
- Why woff2? It won't work in older browsers (but I don't care about this at all).
- Why Vietnamese font? If we add this we should add Greek and so on...
- Why are all font names hashed? This doesn't help at all...
- What is `templates/period_archives.html`?

I think we should use Safe Web Fonts, it would be easier.

**Comment by Phyks** [comment]
>- Why woff2? It won't work in older browsers (but I don't care about
>this at all).

It's what Google Fonts is serving. 

>- Why Vietnamese font? If we add this we should add Greek and so on...

Same. 

>- Why are all font names hashed? This doesn't help at all...

Basically, I just downloaded the CSS file which was served by Google fonts as fonts.css and bulk downloaded the fonts files linked in this stylesheet. 

>- What is `templates/period_archives.html`?

It is for archives covering period of time. Typically monthly and yearly archives. Without this file, such archives pages were not rendering well, they were missing a left margin. 
-- 
Phyks

**Comment by alexandrevicenzi** [comment]
Sorry, can't accept this. The solution for the local font is far away from good. You just copied the CSS generated for Google Chrome, it won't work on IE.

I used Google Fonts for a reason, and I won't change this. The best solution for local fonts is to use Safe Web Fonts.

Also, you put 3 different things in one single PR.

**Comment by Phyks** [comment]
> Also, you put 3 different things in one single PR.

How many PRs / with which content do you want? All of this was discussed in related issues and I thought you agreed on the proposed solutions, then I did a single PR to ease everything, both the reviewing, the dev and the merge.


> Sorry, can't accept this. The solution for the local font is far away from good. You just copied the CSS generated for Google Chrome, it won't work on IE.
> 
> I used Google Fonts for a reason, and I won't change this. The best solution for local fonts is to use Safe Web Fonts.

Sorry, I am not a web designer, and I never had to deal with web hosted fonts. That said, Google Fonts API is not an acceptable solution for me neither. I host my blog, I can host everything myself without having to send each and any of my visitors to Google's servers just to get some font. Of course, there is a (minor) performance gain in using the Google hosted version (and some comfort for the dev), but it also raises a lot of concerns (privacy, but also the fact that they can serve whatever CSS they want), without mentioning the fact that Google Fonts becomes SPOF.

That being said, I came across [this website](https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=vietnamese,latin-ext,latin) which gives:

```css
/* source-sans-pro-300 - latin_latin-ext_vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 300;
  src: url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.eot'); /* IE9 Compat Modes */
  src: local('Source Sans Pro Light'), local('SourceSansPro-Light'),
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.woff') format('woff'), /* Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-300.svg#SourceSansPro') format('svg'); /* Legacy iOS */
}

/* source-sans-pro-regular - latin_latin-ext_vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.eot'); /* IE9 Compat Modes */
  src: local('Source Sans Pro'), local('SourceSansPro-Regular'),
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-regular.svg#SourceSansPro') format('svg'); /* Legacy iOS */
}

/* source-sans-pro-italic - latin_latin-ext_vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: italic;
  font-weight: 400;
  src: url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.eot'); /* IE9 Compat Modes */
  src: local('Source Sans Pro Italic'), local('SourceSansPro-It'),
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.woff') format('woff'), /* Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-italic.svg#SourceSansPro') format('svg'); /* Legacy iOS */
}

/* source-sans-pro-700 - latin_latin-ext_vietnamese */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 700;
  src: url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.eot'); /* IE9 Compat Modes */
  src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'),
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.woff') format('woff'), /* Modern Browsers */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/source-sans-pro-v9-latin_latin-ext_vietnamese-700.svg#SourceSansPro') format('svg'); /* Legacy iOS */
}
```

With the following fonts zip to download: https://google-webfonts-helper.herokuapp.com/api/fonts/source-sans-pro?download=zip&subsets=latin,latin-ext,vietnamese&variants=300,700,italic,regular.

I guess this should just do the job.

**Comment by alexandrevicenzi** [comment]
I just want PRs for each fix, is more readable, one PR for Pygments fix, another for Google Fonts and so on.

Using a solution that uses eot, woff, woff2 would work for almost all browsers available. What I mean for Safe Web Fonts it that you use fonts already on the computer, [this](https://www.w3schools.com/cssref/css_websafe_fonts.asp) and [this](http://web.mit.edu/jmorzins/www/fonts.html) could explain about.

What I'll accept?

 - Single PRs for each fix
- A good fix for Google Fonts that will cover Firefox, Chrome (blink and webkit based browsers), IE (because it's what's win7 users have) and EDGE.

**Comment by Phyks** [comment]
Closing, superseeded by individual PRs as requested.

**Pull request closed without merging**
