### PR TITLE
Set up gulp watch

### LINKED ISSUE #226: Development: update / add gulp tasks
Hi,
I modify dark theme in a previous PR #225, and `USE_LESS` variable doesn't work with `dark-theme.less`. Plus, now Flex have a JavaScript file which interact with the style of the page.

## Problematic
Dark theme files aren't refresh when you use `USE_LESS` variable.
Theses files should be watch:

* `static/stylesheet/dark-theme.less`
* `static/dark-theme/dark-theme.js`

## Proposed solution
Since `USE_LESS` variable is design for testing purposes, why not to watch files and use not minify versions ? Then replace `USE_LESS` variable by `NOT_MINIFY` (or something like that) and add watch task to gulp like:

```js
gulp.task('watch-less', function () {
    return gulp.watch("static/stylesheet/*.less", gulp.task("less"));
});

gulp.task('watch', gulp.series('default', 'watch-less'));
```

## Optional

* Write more modern JavaScript in gulpfile using arrow function, use `const` instead of `var`.
* Add `watch` script in `package.json` to call `watch` gulp task.

### PR DESCRIPTION
**Pull request by haplo**
This is working for me for the regular theme, I haven't tested the dark theme.

Fixes #226.

### CODE REVIEW

**Comment by haplo** [comment]
@lpenaud Would be nice if you could reword the commit message to something more meaningful, e.g. "Set up gulp watch". :pray:

**Comment by lpenaud** [comment]
Hi @haplo thanks you for your interest about this old branch 😄. 
It's been a while since I've work on this project. However I still have the repo cloned on my computer, so I will rebase my commit and test the task with the dark theme. In my memory, It's works.

**Comment by haplo** [comment]
Thank you for being responsive @lpenaud! I can also help with any finishing touches, I just like respecting original authorship whenever possible. :)

**Comment by lpenaud** [comment]
I rewrote my commit.
Gulp watch all less files in `static/stylesheet` included the dark-theme with the JavaScript files without the minify version.

**Comment by haplo** [comment]
Works well for me, thanks for the update!

**Review by alexandrevicenzi — APPROVED** [review]

**Pull request merged**
