### PR TITLE
Initial support for the related_posts plugin.

### PR DESCRIPTION
**Pull request by elementalvoid**
@alexandrevicenzi
If you want it, I added basic support for the [related_posts](https://github.com/getpelican/pelican-plugins/tree/master/related_posts) plugin. It will automatically disable itself if the plugin is not enabled.

However, I don't think you'll like the DOM container that I put it in. : ) Please suggest something better than 'footer' and I'll update it. I say this because it isn't actually in the footer but I got a nice horizontal separator for free by putting it in a footer element.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@elementalvoid, yeah, I dislike the `footer` element. It doesn't looks semantic inside an `article` element.

Maybe the horizontal separator could be done with an `hr` element, or just some CSS stuff. You could give a try, or if not, I could take a look too.

By the way, I liked this idea :smile:

**Comment by elementalvoid** [comment]
Okay, I'll rework without the `footer`.

**Comment by elementalvoid** [comment]
Bump.. What do you think @alexandrevicenzi?

**Comment by alexandrevicenzi** [comment]
@elementalvoid The code looks good, but how it's looks like (screenshot) and how do I setup this?

**Comment by elementalvoid** [comment]
screen shot

To enable it you need to install the [related_posts](https://github.com/getpelican/pelican-plugins/tree/master/related_posts) plugin and then add `PLUGINS = ['related_posts']` to `pelicanconf.py`.

**Comment by alexandrevicenzi** [comment]
Good job @elementalvoid

**Comment by alexandrevicenzi** [comment]
@elementalvoid is it ok to merge?

I think this could be a little bit more beauty, like [this](https://mythemeshop.com/wp-content/uploads/2012/07/Urban-related-posts.png) example.

Do you think is it common to have covers on posts? I don't think so. Maybe we could use post title and some summary. Or just keep this way. Not sure whats the best option here.

**Comment by elementalvoid** [comment]
My personal preference would be to leave it as is. I don't use cover images nor do I think that it's common to use post cover images. At least not on blogs that are using Pelican.

I could see supporting summaries as an optional thing. I'm happy with just the title though.

**Comment by alexandrevicenzi** [comment]
Thanks @elementalvoid.

**Pull request merged**
