### PR TITLE
Add russian translations

### PR DESCRIPTION
**Pull request by groundflyer**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@groundflyer Thanks. Is it on Transifex right?

**Comment by groundflyer** [comment]
I requested to join the team on Transifex, but I hadn't time to wait approval so I translated it manually the way it's described on the wiki.

**Comment by alexandrevicenzi** [comment]
@groundflyer You can upload to transifex now.

**Comment by groundflyer** [comment]
I've added translations to Transifex.

**Pull request merged**
