### PR TITLE
Disqus and sidebar links configuration

### PR DESCRIPTION
**Pull request by alkhimey**
1. Add disqus comment counter (http://imgur.com/a/SZqi1)
2. Add usage of disqus_url to specify which comments to load.
3. Add DISABLE_PAGE_LINKS and DISABLE_PAGE_BLANK_TARGET configuration parameters.

### CODE REVIEW

**Comment by alkhimey** [comment]
Notice that I did not add tests for these features. Not sure how to do this.

**Comment by alexandrevicenzi** [comment]
So, your image shows a broken layout.

And why is a button showing the comment count? Why don't you put in the header? Like:

Posted on November 16, 2016 in News • 1 min read • 10 comments

**Comment by alkhimey** [comment]
@alexandrevicenzi  I changed the location of the link according to your suggestion. Also added it into the header in the article itself. 

http://imgur.com/a/WY1QG

**Comment by alexandrevicenzi** [comment]
-  You sent 2 different things in only one PR.
- I don't want disqus count on my blog, it doesn't work! So, you need to add some flag  `DISQUS_POST_COUNT = True` somewhere to enable this.
- Flex has enough settings if you don't want pages or links why just don't hide your pages?

**Comment by alkhimey** [comment]
No problem adding the ```DISQUS_COMMENT_COUNT``` parameter.
Can you describe what exactly is not working with the disqus count?

Regarding ```DISABLE_PAGE_LINKS```, setting  ```:status: hidden``` on all pages has the desired effect, so I will remove this parameter.

**Comment by alexandrevicenzi** [comment]
@alkhimey is this still valid?

**Comment by alkhimey** [comment]
@alexandrevicenzi What do you  mean? There is an open pull request.

**Comment by alexandrevicenzi** [comment]
@alkhimey yeah, because is open since 2017, the question is, is this still wanted?

**Comment by alkhimey** [comment]
It depends on whether you want it or not.

For my blog I am using a version of the theme that was stable two years ago  including these changes. So personally I good.

**Pull request closed without merging**
