### PR TITLE
Localization support for Flex theme

### LINKED ISSUE #43: Theme translations
Pelican supports translation. Flex is only in English, if someone want to use in pt-BR it need to edit the theme.

It's good to not break things if use i18n.

[Jinja way to translate](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/localizing_using_jinja2.rst)

### PR DESCRIPTION
**Pull request by marcelhuth**
I added support for localization. This should fix #43 

Please keep in mind that there are a couple of changes necessary in your pelican.conf to enable all the stuff. Overview can be found here: [Jinja2 localization in Pelican](https://github.com/getpelican/pelican-plugins/blob/master/i18n_subsites/localizing_using_jinja2.rst)

If you like I can document all the stuff in your repo's wiki. @alexandrevicenzi just let me know.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
Very nice @marcelhuth, but how do I use? Do I need to add new packages or it's just a config on pelican.conf?

I know that this is probably a change that will break stuff, but it's something very useful.

There's some error on CI:

`CRITICAL: TemplateSyntaxError: Encountered unknown tag 'trans'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.`

Could you take a look and make test pass?

**Comment by marcelhuth** [comment]
I've seen this and I know why this is happening, unfortunately I've no "good" solution for this.

The syntax error is caused by not using the JINJA2_EXTENSIONS for i18n in tests/pelicanconf.py, that could be fixed easily by adding this to the config file. The error that follows is:
`CRITICAL: UndefinedError: 'gettext' is undefined` which says we don't have the necessary modules of the plugin i18n_subsites. If you import this the check passes.

Nevertheless, importing a plugin in a theme's check  is not straight forward. Don't know if it would be a solution to have the plugin source in tests folder to do the import a have the checks pass. In my opinion this is a bad solution. Probably we could link i18n_subsites plugin into tests folder of the theme so we can import the plugin for testing.

@alexandrevicenzi what do you think?

**Comment by marcelhuth** [comment]
Hi @alexandrevicenzi ,
do you see any chance to get the installation of i18n_subsites pelican plugin into the Travic CI test. Would it be possible to add something like
```
git clone https://github.com/getpelican/pelican-plugins plugins
```
to the `scripts` area of `.travis.yml` to have the needed i18n_subsites plugin available for testing? If yes, the failing test could be fixed easily with adding something like
```
PLUGIN_PATHS = ['plugins']
PLUGINS = ['i18n_subsites']
JINJA_EXTENSIONS = ['jinja2.ext.i18n']
```
to `tests/pelicanconf.py`

Unfortunately I've no Travic CI option at the moment to test this on my own. :(

**Comment by marcelhuth** [comment]
Okay, Travis CI seems to be quite cool and easy to use, even for me as a first time user :) Tested and runs successful now.
I had to edit your `.travis.yml` file to clone pelican-plugins and added support for i18n in `tests/pelicanconf.py`
Please have a look and let me know if this can be used. I'll try to get all the documentation on how to use everything during the week (won't get it before Tuesday/Wednesday, Sorry). Is it possible (and wanted ;) ) to write to the Wiki in your repo?

**Comment by alexandrevicenzi** [comment]
@marcelhuth Yes, I think Wiki is open for anyone. If not let me know. I'll take a look in the code this week took.

Thanks. :smile:

**Comment by marcelhuth** [comment]
@alexandrevicenzi I added a small documentation for the i18n stuff in your Wiki. Probably that helps for testing. See [here](https://github.com/alexandrevicenzi/Flex/wiki/Multi-language-support)

I think we won't have a chance to get multi-language support without i18n_subsites plugin. The other option that comes to my mind would be maintain more than one version of Flex theme in different languages what is probably leading to conflicting versions. Having the plugin is kind of mandatory with this version, unfortunately. Without the plugin and jinja2 extension the theme cannot be used as the `{% trans %}`-tags are unknown to the jinja2-engine :(

**Comment by alexandrevicenzi** [comment]
@marcelhuth Yes, I know. Do you know any other theme that support i18n? We could get some help from another.

I didn't had time to look you code yet, but I'll do this week.

**Comment by marcelhuth** [comment]
I had a look through pelican-themes repo, search for "trans" (the tag name in the html-files) had no results. So, my guess is, there's no other theme that supports multi-language in the base version.

**Comment by alexandrevicenzi** [comment]
@marcelhuth I found a way to bypass i18n :)

```python
import jinja2.ext

class ByPassTrans(jinja2.ext.InternationalizationExtension):

    def __init__(self, environment):
      super(ByPassTrans, self).__init__(environment)
      self._install_null()

JINJA_EXTENSIONS = [ByPassTrans]
```

**Pull request merged**
