### PR TITLE
Fix Monokai CSS file

### PR DESCRIPTION
**Pull request by Phyks**
Monokai fix, as already discussed.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
If I re-run the command line to generate the CSS files for Pygments will this be overridden?

If so, I guess this is not the solution.

**Comment by Phyks** [comment]
Indeed, the root of the problem is deeper, and I did not find a way to fix the script itself. I just did a monkey patching to "make it work", according to https://github.com/alexandrevicenzi/Flex/issues/119#issuecomment-303151588.

Thanks

**Comment by alexandrevicenzi** [comment]
Yes, I think the problem is the CSS colors of Flex, we should make some changes when using `pre` or `code` tags.

**Comment by alexandrevicenzi** [comment]
Do you have a before and after to see how things look like?

**Comment by Phyks** [comment]
Before is here: https://cloud.githubusercontent.com/assets/3856586/26027365/2a8e4e2a-380d-11e7-941e-63f310c2d8b2.png

After is viewable on my blog: https://phyks.me/2017/04/filtering-ads-with-your-raspberry-pi.html#filtering-ads-with-your-raspberry-pi

**Comment by alexandrevicenzi** [comment]
@Phyks I did a hack on my blog to fix this problem (lol).

So, the problem is with Pygments, not Flex. Pygments doesn't export the default text color, just for keywords. This will be a problem with others styles, not just Monokay.

I already did a hack on [pygments generator](https://github.com/alexandrevicenzi/Flex/blob/master/pygments/generate.py) to fix a related issue, maybe it's time to take a look into it.

**Pull request closed without merging**
