### PR TITLE
Add variable DISABLE_URL_HASH for pretty URL in browser

### PR DESCRIPTION
**Pull request by dmytrolitvinov**
@alexandrevicenzi Add variable **DISABLE_HASH_URL** as a config for pretty URL if need. 
Issue: #77

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
`DISABLE_HASH_URL` or `DISABLE_URL_HASH`? :thinking:

**Comment by dmytrolitvinov** [comment]
@alexandrevicenzi Changed.

**Comment by alexandrevicenzi** [comment]
@dmytrolitvinov could you add this config to the Wiki?

**Comment by dmytrolitvinov** [comment]
@alexandrevicenzi Done. Thanks for merge :)

**Pull request merged**
