### PR TITLE
Making pygments works correctly

### PR DESCRIPTION
**Pull request by cassiobotaro**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
This is pointless, I'm working on it. It's not finished.

**Comment by cassiobotaro** [comment]
Please, until implement this feature, remove from wiki  or add some warning to avoid headache.

**Comment by alexandrevicenzi** [comment]
I was working on it until I decide to ride my bike. I forgot to push. Now it's ok I think.

**Comment by cassiobotaro** [comment]
Ok. Good job @alexandrevicenzi !

**Pull request closed without merging**
