### PR TITLE
show summary for articles in index.html

### PR DESCRIPTION
**Pull request by jgsogo**
User can choose between showing just the summary for each article or the full content with config variable `SUMMARY_MAX_LENGTH` ([see in docs](http://docs.getpelican.com/en/3.6.0/settings.html))

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
This conflict with being able to choose what post will be summarised or not.

You can choose to show the entire content for most posts, but for just one you can show the summary. Removing this options all posts will be summarised or not.

**Comment by jgsogo** [comment]
Maybe I didn't understand what was the intention of
```
{% if summarise or article.metadata['summary'] or article.metadata['summarize'] %}
```
I didn't found any of those variable documented (metadata is, but not its content).

----

With this PR you are able to select which post to summarize:

### pelicanconf.py
By default all content will be shown
```python
# SUMMARY_MAX_LENGTH = 0  # Commented or value = 0: all content as summary
```

### article-summarized.md
If you want to summarize an article you have to write the _Summary_.
````markdown
Title: Summarized article
Summary: This is the summary

This article is being summarized at index.
```

### article-not-summarized.md
Otherwise all content will be shown
````markdown
Title: Not Summarized article

This article won't be summarized, so all this content will be shown in the index.
```

Isn't it intended to work this way?

**Comment by alexandrevicenzi** [comment]
I made this new metadata variable to be able to choose when an article is summarized.

If i set the conf in pelicanconf.py, all posts will be summarized. If I set Summary metadata, I'm able to specify just a single line.

I'm not sure what's the better option in this case, both are correct I think. This new metadata is only available for Flex theme, as og_locale metadata.

**Comment by jgsogo** [comment]
Hi! Sorry for dissapearing during such a long time...

I prefer to stick to official metadata, this way people can switch from one theme to another and will have the same behavior/structure/appearance, I think this is important. Specific metadata can be added to a particular theme for a very particular need but always squeezing the possibilities available.

**Comment by alexandrevicenzi** [comment]
Sure, this is a good point, I need to take a look. By now I'm too busy, but soon I'll made some changes :+1:

**Comment by jgsogo** [comment]
Dedicated branch for this pull-request: #10 This should be the way from the beginning.

**Pull request closed without merging**
