### PR TITLE
Translation menu in top-right

### PR DESCRIPTION
**Pull request by maparent**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@maparent check your code, the build failed.

BTW, what does this do? Is something related with multi-lingual sites ?

**Comment by maparent** [comment]
Sorry for having missed the error.
Yes, it shows a simple language menu on the top-right if there are multiple versions of a page or article, to navigate between translations.

**Comment by alexandrevicenzi** [comment]
@maparent this PR was lost and now is broken. :disappointed: 

Could resolve the conflict?

**Comment by maparent** [comment]
the conflict was only with the uglified file, as far as I could tell.

**Comment by alexandrevicenzi** [comment]
@maparent Pelican translation doesn't work. I followed the steps on doc, but I get an error.

Could you give me examples how you made it work?

**Pull request merged**
